package com.acon.acon.core.analytics.constants

data object PropertyKeys {

    const val SIGN_IN_OR_NOT = "did_login?"
    const val CLICK_TOGGLE = "click_toggle?"
    const val CLICK_HOME_NAVIGATION = "click_home_navigation?"
    const val CLICK_FILTER = "click_filter?"
    const val CLICK_DETAIL_TAG_RANK = "click_detail_tag_rank?"
    const val CLICK_DETAIL_TAG_LOCAL = "click_detail_tag_local?"
    const val CLICK_DETAIL_TAG_NEW = "click_detail_tag_new?"
    const val CLICK_DETAIL_TAG_NONE = "click_detail_tag_none?"
    const val CLICK_FILTER_TYPE_RESTAURANT = "click_filter_type_restaurant?"
    const val CLICK_FILTER_TIME_RESTAURANT = "click_filter_time_restaurant?"
    const val RECORD_FILTER_TIME_RESTAURANT = "record_filter_time_restaurant"
    const val CLICK_FILTER_PRICE_RESTAURANT = "click_filter_price_restaurant?"
    const val CLICK_FILTER_TYPE_CAFE = "click_filter_type_cafe?"
    const val CLICK_FILTER_TIME_CAFE = "click_filter_time_cafe?"
    const val RECORD_FILTER_TIME_CAFE = "record_filter_time_cafe"
    const val CLICK_UPLOAD_NEXT = "click_upload_next?"
    const val SPOT_ID = "spot_id"
    const val CLICK_REVIEW_ACON = "click_review_acon?"
    const val CLICK_REGISTER_FORM = "click_register_form?"
    const val CLICK_TOGGLE_GUEST = "click_toggle_guest?"
    const val GUEST_DURATION = "guest_duration"
    const val CLICK_HOME_NAVIGATION_GUEST = "click_home_navigation_guest?"
    const val CLICK_DETAIL_GUEST = "click_detail_guest?"
    const val CLICK_LOCKED_DETAIL_GUEST = "click_locked_detail_guest?"
    const val CLICK_UPLOAD_GUEST = "click_upload_guest?"
    const val CLICK_SHARE = "click_share?"
    const val CLICK_DETAIL_NAVIGATION = "click_detail_navigation?"
    const val CLICK_REPORT_ERROR = "click_report_error?"
    const val PLACE_DETAIL_DURATION = "place_detail_duration"
    const val CLICK_EXIT_SERVICE = "click_exit_service?"
    const val EXIT_REASON = "exit_reason"
    const val DELETE_ID = "delete_id"
    const val CLICK_SIGN_OUT = "click_logout?"
}