name: '이슈 생성'
title: '이슈 제목'
body:
  - type: input
    id: dueDate
    attributes:
      label: '🗓️ 마감일'
      placeholder: '2025-05-07'
    validations:
      required: false
      
  - type: textarea
    id: description
    attributes:
      label: '📝 상세 내용'
      description: '이슈에 대해서 설명해주세요'
    validations:
      required: false
